name: docker

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/docker.yml"
env:
  VERSION: 0.9.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Development
        uses: docker/build-push-action@v2
        with:
          context: ./docker/development
          build-args: |
            VERSION=${{ env.VERSION }}
            ARCH=amd64
          push: true
          tags: yaoapp/yao:${{ env.VERSION }}-amd64-dev

      - name: Build Development Arm64
        uses: docker/build-push-action@v2
        with:
          context: ./docker/development
          build-args: |
            VERSION=${{ env.VERSION }} 
            ARCH=arm64
          push: true
          tags: yaoapp/yao:${{ env.VERSION }}-arm64-dev

      - name: Build Production
        uses: docker/build-push-action@v2
        with:
          context: ./docker/production
          build-args: |
            VERSION=${{ env.VERSION }} 
            ARCH=amd64
          push: true
          tags: yaoapp/yao:${{ env.VERSION }}-amd64

      - name: Build Production Arm64
        uses: docker/build-push-action@v2
        with:
          context: ./docker/production
          build-args: |
            VERSION=${{ env.VERSION }} 
            ARCH=arm64
          push: true
          tags: yaoapp/yao:${{ env.VERSION }}-arm64
